http://localhost:8080/hello

###

http://localhost:8080/api/points/account-100/balance

###

POST http://localhost:8080/api/points/account-100/earn
Content-Type: application/json

{
  "purchaseId": "order-122"
}

###

POST http://localhost:8080/api/points/account-100/earn
Content-Type: application/json

{
  "purchaseId": "order-123"
}

###

POST http://localhost:8080/api/points/account-100/earn
Content-Type: application/json

{
  "purchaseId": "order-124"
}

###

POST http://localhost:8080/api/points/account-101/earn
Content-Type: application/json

{
  "purchaseId": "order-125"
}

### 

POST http://localhost:8080/api/points/account-100/redeem
Content-Type: application/json

{
  "rewardId": "free-coffee"
}

### 

POST http://localhost:8080/api/points/account-101/redeem
Content-Type: application/json

{
  "rewardId": "free-coffee"
}

###

POST http://localhost:8080/api/points/account-100/clawback
Content-Type: application/json

{
  "purchaseId": "order-124"
}
