spring.application.name=loyalty_points_service
spring.web.error.include-message=always
spring.datasource.url=jdbc:sqlite:loyalty_points.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Defer initialization of the datasource until after the JPA entities have been
# created.
spring.jpa.defer-datasource-initialization=true

# Setting this to always ensures that the data.sql file is executed on startup.
# We use this to pre-populate the db with some sample data for testing.
spring.sql.init.mode=always

# Turn on debug logging for ScriptUtils to see the SQL statements being executed
# from data.sql.
logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG
